function [ obj, numWarnings, warnings ] = loadEuronav(obj, filename, varargin)
%LOADEURONAV Summary of this function goes here
%   Detailed explanation goes here

% validateattributes(imo, {'numeric'}, {'scalar', 'positive', 'integer'}, ...
%    'cVessel.loadDNVGLReportingFormat', 'imo', 3);
% set2_sql = ['IMO_Vessel_Number = ', num2str(imo)];

filename = validateCellStr(filename, 'loadEuronav', 'filename', 2);

readSheets_l = true;
if nargin > 2
    
    sheetname = varargin{2};
    sheetname = validateCellStr(sheetname, 'loadEuronav', 'sheetname', 3);
    readSheets_l = false;
end


for fi = 1:numel(filename)
    
    currFile = filename{fi};
    
    if readSheets_l
        
        [~, sheetname] = xlsfinfo(currFile);
    end
    
    for si = 1:numel(sheetname)
        
        currSheet = sheetname{si};
        
        p = inputParser();
        p.addParameter('firstRowIdx', 2);
        p.addParameter('fileColID', [1, 2, 3, 4, 5, 6, 7, 15, 24, 25, 26, 27, 28, 29, 30, 33, 22, 23, 31]);  %, 22, 23, 24, 25, 26, 27]); % 8, 11, 14
        p.addParameter('tab', 'RawData');
        p.addParameter('fileColName', {  ...
                        'Vessel',...
                        'StartTime',...
                        'EndTime',...
                        'Shaft_Revolutions',...
                        'Shaft_Torque',...
                        'Static_Draught_Fore',...
                        'Static_Draught_Aft',...
                        'Temp_Fuel_Oil_At_Flow_Meter',...
                        'GPS_Speed',...
                        'Speed_Through_Water',  ...
                        'Ship_Heading',...
                        'Rudder_Angle',...
                        'Wind_Speed_Knots',...
                        'Relative_Wind_Direction',...
                        'Water_Depth',...
                        'Mass_Consumed_Fuel_Oil'  ...
                        'Latitude',...
                        'Longitude',...
                        'Shaft_Power',...
                                   });
    %     p.addParameter('tabColNames', {  ...
    %                     'DateTime_UTC', ...
    %                     'Shaft_Revolutions',...
    %                     'Shaft_Torque',...
    %                     'Static_Draught_Fore',...
    %                     'Static_Draught_Aft',...
    %                     'Temp_Fuel_Oil_At_Flow_Meter',...
    %                     'Mass_Consumed_Fuel_Oil',...
    %                     'Speed_Over_Ground',...
    %                     'Relative_Wind_Speed',  ...
    %                     'Relative_Wind_Direction',...
    %                     'Speed_Through_Water',...
    %                     'Water_Depth',...
    %                     'Ship_Heading',...
    %                     'Rudder_Angle'...
    %                     'Shaft_Power'...
    %                                });
        
        p.addParameter('SetSQL', ...
                    {'Timestamp = STR_TO_DATE(@StartTime, ''%d-%m-%Y %H:%i:%s'') + timeDIFF(STR_TO_DATE(@EndTime, ''%d-%m-%Y %H:%i:%s''), STR_TO_DATE(@StartTime, ''%d-%m-%Y %H:%i:%s''))/2',...
                    ['Vessel_Id = CASE '...
                    'WHEN @Vessel = ''Hakone'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9398084)',...
                    'WHEN @Vessel = ''Hirado'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9377420)',...
                    'WHEN @Vessel = ''Hakata'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9346952)',...
                    'WHEN @Vessel = ''Hakone'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9398084)',...
                    'WHEN @Vessel = ''Sandra'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9537757)',...
                    'WHEN @Vessel = ''Sara'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9537745)',...
                    'WHEN @Vessel = ''Devon'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9516117)',...
                    'WHEN @Vessel = ''Maria'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9530890)',...
                    'WHEN @Vessel = ''Captain Michael'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9531480)',...
                    'WHEN @Vessel = ''Aquitaine'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9732577)',...
                    'WHEN @Vessel = ''Ardeche'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9732565)',...
                    'WHEN @Vessel = ''Cap Charles'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9321706)',...
                    'WHEN @Vessel = ''Cap Guillaume'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9321691)',...
                    'WHEN @Vessel = ''Cap Lara'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9330874)',...
                    'WHEN @Vessel = ''Cap Philippe'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9321718)',...
                    'WHEN @Vessel = ''Cap Victor'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9321720)',...
                    'WHEN @Vessel = ''Simone'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9537769)',...
                    'WHEN @Vessel = ''Sonia'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9537771)',...
                    'WHEN @Vessel = ''TI Hellas'' THEN (SELECT Vessel_Id FROM Vessel WHERE IMO = 9290086)',...
                    'END']...
                    'Speed_Over_Ground = knots2mps(@GPS_Speed)'...
                    'Relative_Wind_Speed = knots2mps(@Wind_Speed_Knots)'....
                    'Speed_Through_Water = knots2mps(@Speed_Through_Water)'....
                    });
        paramValues_c = varargin;
        p.parse(paramValues_c{:});
    %     mainSheet = p.Results.mainSheet;
        firstRowIdx = p.Results.firstRowIdx;
        fileColID = p.Results.fileColID;
        tab = p.Results.tab;
        fileColName = p.Results.fileColName;
    %     tabColNames = p.Results.tabColNames;
        SetSQL = p.Results.SetSQL;

        % Concatenate all set commands
    %     SetSQL = [SetSQL, set2_sql];

        % Load time-seres data from xlsx
        [obj, numWarnings, warnings] = obj.loadXLSX(currFile, currSheet, firstRowIdx, fileColID, fileColName, tab, SetSQL);
    end
end