function [ obj, numWarnings, warnings ] = loadBergeNoon(obj, filename, sheetname, basedate, varargin)
%loadBergeNoon Load data from Berge Bulk noon data file
%   Detailed explanation goes here

filename = validateCellStr(filename, 'loadBergeNoon', 'filename', 2);

for fi = 1:numel(filename)

    currFile = filename{fi};
    
    % Input
    sheetDate_l = false;
    if nargin < 3 % isempty(sheetname)

        % Get sheet names matching expected post-2012 pattern 
        [~, sh] = xlsfinfo(currFile);
        sheetNameLog_c = regexp(sh, '\d\d.\d\d');
        sheetDate_l = cellfun(@(x) isequal(x, 1), sheetNameLog_c);

        if ~any(sheetDate_l)

            errid = 'loadBerge:NoSheetPre2012';
            errmsg = ['If sheet names are not input, sheets in file are '...
                'expected to have name format MONTH.DATE'];
            error(errid, errmsg);
        end
        sheetname = sh(sheetDate_l);
    end

    if nargin < 4 && any(sheetDate_l)

        % Get base date from sheet names
        basedate = datenum(sheetname, 'mm.yy');

    elseif nargin < 4 && ~any(sheetDate_l)

        % Cannot get base date from sheet names
        errid = 'loadBerge:NoSheetPre2012NoDate';
        errmsg = ['If file does not contain sheets with names in the '...
            'format MONTH.DATE, input BASEDATE must be given'];
        error(errid, errmsg);
    end
    
    if nargin < 5
        
        lastrow = varargin{1};
    end

    sheetname = validateCellStr(sheetname, 'cVessel.loadBergeNoon', 'sheetname', 1);
    validateattributes(basedate, {'numeric'}, {'real', 'positive', ...
        '>=', datenum('01-01-1950')}, 'cVessel.loadBergeNoon', 'baseDate', 2);

    imo = obj.IMO_Vessel_Number;
    if isempty(imo)

        errid = 'loadBerge:NeedIMO';
        errmsg = ['To load data from file, IMO Vessel Number must be given '...
            'in the appropriate property of OBJ.'];
        error(errid, errmsg);
    end

    if ~isequal(numel(sheetname), numel(basedate))

        errid = 'loadBerge:SheetDateSizeMismatch';
        errmsg = 'Number of sheet names input must match number of base dates';
        error(errid, errmsg);
    end

    % Create SQL date string this sheet
    baseDate_ch = datestr(basedate, 'yyyy-mm-dd');
    baseDate_c = cellstr(baseDate_ch);

    validateattributes(imo, {'numeric'}, {'scalar', 'positive', 'integer'}, ...
       'cVessel.loadDNVGLReportingFormat', 'imo', 3);
    set2_sql = ['IMO_Vessel_Number = ', num2str(imo)];

    for si = 1:numel(sheetname)

        baseDate_ch = baseDate_c{si};
        baseDate_sql = ['STR_TO_DATE(''' baseDate_ch ''', ''%Y-%m-%d'') - 1'] ;

        p = inputParser();
        p.addParameter('mainSheet', 'JAN');
        p.addParameter('firstRowIdx', 7);
        p.addParameter('tab', 'RawData');
        p.addParameter('fileColID', [2, 11, 12, 13, 19, 26, 27, 21, 22]-1);
        p.addParameter('fileColName', {...
                        'DayOfMonth',               ...
                        'Speed_Through_Water',      ...
                        'Wind_Force',               ...
                        'Wind_Angle',  ...
                        'Delivered_Power',          ...
                        'Static_Draught_Fore',      ...
                        'Static_Draught_Aft'        ...
                        'MECons'                    ...
                        'AECons'                    ...
                                   });
%         p.addParameter('tabColNames', {             ...
%                         'DateTime_UTC',             ...
%                         'Speed_Over_Ground',        ...
%                         'Relative_Wind_Speed',      ...
%                         'Relative_Wind_Direction',  ...
%                         'Delivered_Power',          ...
%                         'Mass_Consumed_Fuel_Oil',   ...
%                         'Static_Draught_Fore',      ...
%                         'Static_Draught_Aft'        ...
%                         'Speed_Through_Water'
%                                    });
        p.addParameter('SetSQL', ...
                    {['DateTime_UTC = nullif(STR_TO_DATE(@DayOfMonth, ''%d'') + ' '' baseDate_sql ', ''0000-00-00 00:00:00.000'')'],...
                    'Speed_Through_Water = nullif(knots2mps(@Speed_Through_Water), ''-'')',...
                    ['Relative_Wind_Speed = CASE '...
                    'WHEN @Wind_Force = '''' THEN NULL ',...
                    'WHEN @Wind_Force = 0 THEN 0.1500 ',...
                    'WHEN @Wind_Force = 1 THEN 0.9 ',...
                    'WHEN @Wind_Force = 2 THEN 2.45 ',...
                    'WHEN @Wind_Force = 3 THEN 4.45 ',...
                    'WHEN @Wind_Force = 4 THEN 6.7 ',...
                    'WHEN @Wind_Force = 5 THEN 9.35 ',...
                    'WHEN @Wind_Force = 6 THEN 12.3 ',...
                    'WHEN @Wind_Force = 7 THEN 15.5 ',...
                    'WHEN @Wind_Force = 8 THEN 18.95 ',...
                    'WHEN @Wind_Force = 9 THEN 22.6 ',...
                    'WHEN @Wind_Force = 10 THEN 26.45 ',...
                    'WHEN @Wind_Force = 11 THEN 30.55 ',...
                    'WHEN @Wind_Force = 12 THEN 34.7 ',...
                    'WHEN CONCAT('''',@Wind_Force * 1) = @Wind_Force THEN @Wind_Force ',...
                    'END']...
                    'Mass_Consumed_Fuel_Oil = nullif(@MECons, '''') + nullif(@AECons, '''')',...
                    ['Relative_Wind_Direction = CASE '...
                    'WHEN @Wind_Angle = '''' THEN NULL ',...
                    'WHEN @Wind_Angle = ''N'' THEN 0 ',...
                    'WHEN @Wind_Angle = ''NNE'' THEN 22.5 ',...
                    'WHEN @Wind_Angle = ''NE'' THEN 45 ',...
                    'WHEN @Wind_Angle = ''ENE'' THEN 67.5 ',...
                    'WHEN @Wind_Angle = ''E'' THEN 90 ',...
                    'WHEN @Wind_Angle = ''ESE'' THEN 112.5 ',...
                    'WHEN @Wind_Angle = ''SE'' THEN 135 ',...
                    'WHEN @Wind_Angle = ''SSE'' THEN 157.5 ',...
                    'WHEN @Wind_Angle = ''S'' THEN 180 ',...
                    'WHEN @Wind_Angle = ''SSW'' THEN 202.5 ',...
                    'WHEN @Wind_Angle = ''SW'' THEN 225 ',...
                    'WHEN @Wind_Angle = ''WSW'' THEN 247.5 ',...
                    'WHEN @Wind_Angle = ''W'' THEN 270 ',...
                    'WHEN @Wind_Angle = ''WNW'' THEN 292.5 ',...
                    'WHEN @Wind_Angle = ''NW'' THEN 315 ',...
                    'WHEN @Wind_Angle = ''NNW'' THEN 337.5 ',...
                    'WHEN CONCAT('''',@Wind_Angle * 1) = @Wind_Angle THEN @Wind_Angle ',...
                    'END']...
                    });
        p.addParameter('LastRow', 37);
        paramValues_c = varargin;
        p.parse(paramValues_c{:});
    %     mainSheet = p.Results.mainSheet;
        firstRowIdx = p.Results.firstRowIdx;
        fileColID = p.Results.fileColID;
        tab = p.Results.tab;
        fileColName = p.Results.fileColName;
%         tabColNames = p.Results.tabColNames;
        SetSQL = p.Results.SetSQL;
        lastrow = p.Results.LastRow;

        % Concatenate all set commands
        SetSQL = [SetSQL, set2_sql];

        % Load time-seres data from xlsx
        currSheet = sheetname{si};
        [obj, numWarnings, warnings] = obj.loadXLSX(currFile, currSheet, firstRowIdx - 1, fileColID, ...
            fileColName, tab, SetSQL, '', lastrow(si));
    end
end
end