function [obj] = loadTMSNoon(obj, filename)
%loadTMSNoon Load noon data sent by TMS
%   Detailed explanation goes here

filename = validateCellStr(filename, 'loadEuronav', 'filename', 2);

for fi = 1:numel(filename)
    
    currFile = filename{fi};
    p = inputParser();
    p.addParameter('firstRowIdx', 1);
    p.addParameter('fileColID', [2, 11, 12, 15, 16, 27, 28, 45]);
    p.addParameter('tab', 'RawData');
    p.addParameter('fileColName', {  ...
                    'telegram_date',...
                    'Relative_Wind_Direction',...
                    'wind_force',...
                    'Ship_Heading',...
                    'Shaft_Revolutions',...
                    'Static_Draught_Fore',      ...
                    'Static_Draught_Aft',        ...
                    'Mass_Consumed_Fuel_Oil'        ...
                               });
    
    p.addParameter('SetSQL', ...
                {'Timestamp = STR_TO_DATE(@telegram_date, ''%d-%m-%Y %H:%i:%s'')',...
                ['Relative_Wind_Speed = CASE '...
                    'WHEN @Wind_Force = '''' THEN NULL ',...
                    'WHEN @Wind_Force = 0 THEN 0.1500 ',...
                    'WHEN @Wind_Force = 1 THEN 0.9 ',...
                    'WHEN @Wind_Force = 2 THEN 2.45 ',...
                    'WHEN @Wind_Force = 3 THEN 4.45 ',...
                    'WHEN @Wind_Force = 4 THEN 6.7 ',...
                    'WHEN @Wind_Force = 5 THEN 9.35 ',...
                    'WHEN @Wind_Force = 6 THEN 12.3 ',...
                    'WHEN @Wind_Force = 7 THEN 15.5 ',...
                    'WHEN @Wind_Force = 8 THEN 18.95 ',...
                    'WHEN @Wind_Force = 9 THEN 22.6 ',...
                    'WHEN @Wind_Force = 10 THEN 26.45 ',...
                    'WHEN @Wind_Force = 11 THEN 30.55 ',...
                    'WHEN @Wind_Force = 12 THEN 34.7 ',...
                    'WHEN CONCAT('''',@Wind_Force * 1) = @Wind_Force THEN @Wind_Force ',...
                    'END'],...
                'Speed_Over_Ground = knots2mps(@GPS_Speed)'...
                'Relative_Wind_Speed = knots2mps(@Wind_Speed_Knots)'....
                'Speed_Through_Water = knots2mps(@Speed_Through_Water)'....
                });
    paramValues_c = varargin;
    p.parse(paramValues_c{:});

    % Load time-seres data from xlsx
    [obj, numWarnings, warnings] = obj.loadXLSX(currFile, currSheet, firstRowIdx, fileColID, fileColName, tab, SetSQL);
end