function [ obj, numWarnings, warnings ] = loadUASCNoon(obj, filename, varargin)
%loadUASCNoon Load data from UASC noon data file
%   Detailed explanation goes here

% Input
imo = obj.IMO_Vessel_Number;
if isempty(imo)
    
    errid = 'loadUASC:NeedIMO';
    errmsg = ['To load data from file, IMO Vessel Number must be given '...
        'in the appropriate property of OBJ.'];
    error(errid, errmsg);
end

validateattributes(imo, {'numeric'}, {'scalar', 'positive', 'integer'}, ...
   'cVessel.loadDNVGLReportingFormat', 'imo', 3);
set2_sql = ['IMO_Vessel_Number = ', num2str(imo)];

p = inputParser();
p.addParameter('mainSheet', 'AFRH');
p.addParameter('firstRowIdx', 2);
p.addParameter('fileColID', [1, 15, 16, 31, 32, 47, 54, 67, 69]);
p.addParameter('tab', 'RawData');
p.addParameter('fileColName', {  ...
                'Date', ...
                'TRUE COURSE (At Noon)',...
                'Wind_Dir_Force',...
                'Static_Draught_Fore',...
                'Static_Draught_Aft',...
                'Delivered_Power',  ...
                'Speed_Through_Water',  ...
                'MECons_1',  ...
                'MECons_2'  ...
                           });
% p.addParameter('tabColNames', {  ...
%                 'DateTime_UTC', ...
%                 'Ship_Heading',...
%                 'Relative_Wind_Direction',...
%                 'Relative_Wind_Speed',  ...
%                 'Static_Draught_Fore',  ...
%                 'Static_Draught_Aft',  ...
%                 'Delivered_Power',  ...
%                 'Speed_Through_Water',  ...
%                 'Mass_Consumed_Fuel_Oil'  ...
%                            });
p.addParameter('SetSQL', ...
            {'DateTime_UTC = STR_TO_DATE(@Date, ''%d-%m-%Y'')',...
            'Ship_Heading = nullif(@`TRUE COURSE (At Noon)`, '''')',...
            ['Relative_Wind_Direction = CASE ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''N'' THEN 0 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''NNE'' THEN 22.5 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''NE'' THEN 45 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''ENE'' THEN 67.5 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''E'' THEN 90 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''ESE'' THEN 112.5 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''SE'' THEN 135 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''SSE'' THEN 157.5 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''S'' THEN 180 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''SSW'' THEN 202.5 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''SW'' THEN 225 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''WSW'' THEN 247.5 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''W'' THEN 270 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''WNW'' THEN 292.5 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''NW'' THEN 315 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''NNW'' THEN 337.5 ',...
            'END'],...
            ['Relative_Wind_Speed = CASE '...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 0 THEN 0.1500 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 1 THEN 0.9 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 2 THEN 2.45 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 3 THEN 4.45 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 4 THEN 6.7 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 5 THEN 9.35 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 6 THEN 12.3 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 7 THEN 15.5 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 8 THEN 18.95 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 9 THEN 22.6 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 10 THEN 26.45 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 11 THEN 30.55 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 12 THEN 34.7 ',...
            'END'],...
            'Delivered_Power = LEFT(@Delivered_Power, INSTR(@Delivered_Power, ''KW'')-1) + 0',...
            'Speed_Through_Water = knots2mps(nullif(@Speed_Through_Water, ''''))',...
            'Mass_Consumed_Fuel_Oil = nullif(@MECons_1, '''') + nullif(@MECons_2, '''')'});
paramValues_c = varargin;
p.parse(paramValues_c{:});
mainSheet = p.Results.mainSheet;
firstRowIdx = p.Results.firstRowIdx;
fileColID = p.Results.fileColID;
tab = p.Results.tab;
fileColName = p.Results.fileColName;
% tabColNames = p.Results.tabColNames;
SetSQL = p.Results.SetSQL;

% Concatenate all set commands
SetSQL = [SetSQL, set2_sql];

% % Account for behaviour where 1 row fewer than expected is read
% firstRowIdx = firstRowIdx - 1;

% Load time-seres data from xlsx
[obj, numWarnings, warnings] = obj.loadXLSX(filename, mainSheet, firstRowIdx, fileColID, fileColName, tab, SetSQL);

end