function obj = loadOmanShippingNoon(obj, filename, varargin)
%loadOmanShippingNoon Load noon data from Oman Shipping into database
%   Detailed explanation goes here

% Prep inputs to loadXLSX



% 
mainSheet = 'AS SUWAYQ';
firstRowIdx = 8;
fileColID = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 15, 16, 19, 20, 22, 23];
fileColName = { 'Date', ...
                'Event', ...
                'Time',...
                'Static_Draught_Aft',...
                'Static_Draught_Fore',...
                'Latitude',...
                'Longitude',...
                'Ship_Heading',...
                'Speed_Over_Ground',  ...
                'Speed_Through_Water',  ...
                'Relative_Wind_Direction',  ...
                'Relative_Wind_Speed',  ...
                'Shaft_Power',  ...
                'Shaft_Revolutions',  ...
                'Steaming_Time',  ...
                'Fuel_Cons_Per_Hour',  ...
                'Rudder_Angle',  ...
                'Water_Depth'};
tab = 'RawData';
SetSQL = {'DateTime_UTC = DATE_ADD(STR_TO_DATE(@Date, ''%d-%m-%Y''), INTERVAL @Time*24 HOUR)',...
          'Mass_Consumed_Fuel_Oil = @Steaming_Time*@Fuel_Cons_Per_Hour',...
          'Speed_Over_Ground = knots2mps(@Speed_Over_Ground)',...
          'Speed_Through_Water = knots2mps(@Speed_Through_Water)',...
          'Relative_Wind_Speed = knots2mps(@Relative_Wind_Speed)',...
          'IMO_Vessel_Number = 9500728'};

[obj, numWarnings, warnings] = obj.loadXLSX(filename, mainSheet, firstRowIdx, fileColID, fileColName, tab, SetSQL);

obj.SQL.execute('DELETE FROM RawData WHERE IMO_Vessel_Number = 9500728 AND Relative_Wind_Direction IS NULL;');
obj.SQL.execute('DELETE FROM RawData WHERE IMO_Vessel_Number = 9500728 AND DateTime_UTC < ''2016-11-20 00:00:00.000'';');
% obj.execute('UPDATE RawData SET Displacement = 1e5 WHERE IMO_Vessel_Number = 9500728 AND (Static_Draught_Fore + Static_Draught_Aft)/2 <= 10;');
% obj.execute('UPDATE RawData SET Displacement = 2e5 WHERE IMO_Vessel_Number = 9500728 AND (Static_Draught_Fore + Static_Draught_Aft)/2 > 10;');


end