function [ obj, numWarnings, warnings ] = loadAMCLRaw(obj, filename, set2_sql)
%loadAMCLRaw Load raw data from AMCL file
%   Detailed explanation goes here
    
    
% Load time-seres data from xlsx
mainSheet = 'TankData';
firstRow = 6;
fileColID = [3, 7, 10, 12, 15, 16, 18, 23, 19, 15, 4, 5, 6];
fileColName = {  ...
                'DateTime_UTC', ...
                'Ship_Heading', ...
                'Speed_Through_Water',  ...
                'Wind_Dir_Force',...
                'Air_Temperature',  ...
                'Seawater_Temperature',  ...
                'Delivered_Power',  ...
                'Fuel_Oil_Cons'  ...
                'Speed_Over_Ground',  ...
                'Shaft_Revolutions',  ...
                'Latitude',  ...
                'Longitude', ...
                'Loading'};  % Loaded draft: 19.2m, Ballast draft: 5m (why not?)
tab = 'RawData';

% Create necessary set SQL
set_sql = [{'DateTime_UTC = STR_TO_DATE(@DateTime_UTC, ''%Y-%m-%d %H:%i'')',...
            ['Relative_Wind_Direction = CASE ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''N'' THEN 0 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''NE'' THEN 45 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''E'' THEN 90 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''SE'' THEN 135 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''S'' THEN 180 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''SW'' THEN 225 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''W'' THEN 270 ',...
            'WHEN LEFT(@Wind_Dir_Force, INSTR(@Wind_Dir_Force, ''/'')-1) = ''NW'' THEN 315 ',...
            'END'],...
            ['Relative_Wind_Speed = CASE '...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 0 THEN 0.1500 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 1 THEN 0.9 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 2 THEN 2.45 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 3 THEN 4.45 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 4 THEN 6.7 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 5 THEN 9.35 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 6 THEN 12.3 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 7 THEN 15.5 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 8 THEN 18.95 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 9 THEN 22.6 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 10 THEN 26.45 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 11 THEN 30.55 ',...
            'WHEN RIGHT(@Wind_Dir_Force, LENGTH(@Wind_Dir_Force) - INSTR(@Wind_Dir_Force, ''/'')) + 0 = 12 THEN 34.7 ',...
            'END'],...
            'Mass_Consumed_Fuel_Oil = LEFT(@Fuel_Oil_Cons, INSTR(@Fuel_Oil_Cons, ''/'')-1) + 0',...
            'Speed_Through_Water = knots2mps(nullif(@Speed_Through_Water, ''''))',...
            ['Latitude = SELECT (LEFT(@Latitude, 2) + MID(@Latitude, 3, 2)/60 + MID(@Latitude, 5, 2)/3600)', ...
                '*(SELECT CASE RIGHT(@Latitude, 1) ', ...
                    'WHEN ''N'' THEN 1 ', ...
                    'WHEN ''S'' THEN -1 ', ...
                    'ELSE NULL ', ...
                        'END)'],...
            ['Longitude = SELECT (LEFT(@Longitude, 3) + MID(@Longitude, 3, 2)/60 + MID(@Longitude, 5, 2)/3600)', ...
                '*(SELECT CASE RIGHT(@Longitude, 1) ', ...
                    'WHEN ''E'' THEN 1 ', ...
                    'WHEN ''W'' THEN -1 ', ...
                    'ELSE NULL ', ...
                        'END)'],...
            'Speed_Over_Ground = knots2mps(nullif(@Speed_Over_Ground, ''''))'},...
            set2_sql];
dateTimeFormat_c = {'DateTime_UTC', 'yyyy-mm-dd HH:MM'};
[obj, numWarnings, warnings] = obj.loadXLSX(filename, mainSheet, firstRow, fileColID, fileColName, tab, set_sql, dateTimeFormat_c);
end