function printImportFile(obj, filename, varargin)
%printImportFile Print file for import into SHAPE
%   Detailed explanation goes here

% Input
validateattributes(filename, {'char'}, {'vector'}, ...
    'cVessel.printImportFile', 'filename', 2);

nonNull = {'Relative_Wind_Direction', 'Relative_Wind_Speed', ...
    'Static_Draught_Fore', 'Static_Draught_Aft', 'Delivered_Power'};
if nargin > 2
    
    nonNull = varargin{1};
    nonNull = validateCellStr(nonNull, 'cVessel.printImportFile', 'nonNull', 3);
end

gtZero = {'Relative_Wind_Direction', 'Relative_Wind_Speed',...
    'Static_Draught_Fore', 'Static_Draught_Aft', 'Delivered_Power'};
if nargin > 3
    
    gtZero = varargin{2};
    gtZero = validateCellStr(gtZero, 'cVessel.printImportFile', 'gtZero', 4);
end

% Put file name in uploads dir
uploadsDir = 'C:\ProgramData\MySQL\MySQL Server 5.7\Uploads';
filename = fullfile(uploadsDir, filename);

% Create where statement with filters
SQL = obj.SQL;
[~, nonNull_c] = cellfun(@(x) SQL.combineSQL('AND', x, 'IS NOT NULL'), ...
    nonNull, 'Uni', 0);
[~, gtZero_c] = cellfun(@(x) SQL.combineSQL('AND', x, ' > 0'), ...
    gtZero, 'Uni', 0);

for oi = 1:numel(obj)
    
    currObj = obj(oi);
    
    % Need vessel id
    vid = currObj.Vessel_Id;
    if isempty(vid)
        
        errid = 'ImportFile:NeedIdentifier';
        errmsg = 'Vessel_Id must be non-empty to print import file';
        error(errid, errmsg)
    end
    
    % Inner-most select
    tab = 'static.RawData';
    cols = {'DATE_FORMAT(Timestamp, ''%Y-%m-%d %H:%i:%s.%f'')',...
	  'ifnull(Relative_Wind_Speed, '''')',...
	  'ifnull(Relative_Wind_Direction, '''')',...
	  'ifnull(Speed_Over_Ground, '''')',...
	  'ifnull(Ship_Heading, '''')',...
	  'ifnull(Shaft_Revolutions, '''')',...
	  'ifnull(Static_Draught_Fore, '''')',...
	  'ifnull(Static_Draught_Aft, '''')',...
	  'ifnull(Water_Depth, '''')',...
	  'ifnull(Rudder_Angle, '''')',...
	  'ifnull(Seawater_Temperature, '''')',...
	  'ifnull(Air_Temperature, '''')',...
	  'ifnull(Air_Pressure, '''')',...
	  'ifnull(Speed_Through_Water, '''')',...
	  'ifnull(Delivered_Power, '''')',...
	  'ifnull(Shaft_Power, '''')',...
	  'ifnull(Brake_Power, '''')',...
	  'ifnull(Shaft_Torque, '''')',...
	  'ifnull(Mass_Consumed_Fuel_Oil, '''')',...
	  'ifnull(Volume_Consumed_Fuel_Oil, '''')',...
	  'ifnull(Temp_Fuel_Oil_At_Flow_Meter, '''')',...
	  'ifnull(Displacement, '''')'};
%     where = ['Timestamp > ''0000-00-00'' AND ',...
%                 nonNull_c{:}, ' ',...
%                 gtZero_c{:}];
    [~, where] = SQL.combineSQL('Timestamp > ''0000-00-00'' AND ', ...
        'Vessel_Id =', num2str(vid),...
        nonNull_c{:}, gtZero_c{:});
    [~, ~, sql] = SQL.select(tab, cols, where);
    [~, sql] = SQL.determinateSQL(sql);
    
    % Concat outer syntax
    sql = strcat('(', sql, ') a');
    [~, ~, sql] = SQL.select(sql, '*');
    [~, sql] = SQL.determinateSQL(sql);
    
    % Concat column headers
    fileHeaders_sql = ['SELECT ''DateTime_UTC'''...
      ',''Relative_Wind_Speed'''...
      ',''Relative_Wind_Direction'''...
      ',''Speed_Over_Ground'''...
      ',''Ship_Heading'''...
      ',''Shaft_Revolutions'''...
      ',''Static_Draught_Fore'''...
      ',''Static_Draught_Aft'''...
      ',''Water_Depth'''...
      ',''Rudder_Angle'''...
      ',''Seawater_Temperature'''...
      ',''Air_Temperature'''...
      ',''Air_Pressure'''...
      ',''Speed_Through_Water'''...
      ',''Delivered_Power'''...
      ',''Shaft_Power'''...
      ',''Brake_Power'''...
      ',''Shaft_Torque'''...
      ',''Mass_Consumed_Fuel_Oil'''...
      ',''Volume_Consumed_Fuel_Oil'''...
      ',''Temp_Fuel_Oil_At_Flow_Meter'''...
      ',''Displacement'''...
        ' UNION ALL'];
    [~, sql] = SQL.combineSQL(fileHeaders_sql, sql);
    
    % Format file name
    formattedfile = SQL.encloseFilename(filename);
    
    % Concat file
    out_sql = 'INTO OUTFILE';
    [~, out_sql] = SQL.combineSQL(out_sql, formattedfile);
    [~, sql] = SQL.combineSQL(sql, out_sql);
    
    % File formatting options
    format_sql = ['FIELDS TERMINATED BY '','''...
                    ' ESCAPED BY '''''...
                        ' ENCLOSED BY '''''...
                            ' LINES TERMINATED BY ''\n'''];
    [~, sql] = SQL.combineSQL(sql, format_sql);
    
    % Terminate
    [~, sql] = SQL.terminateSQL(sql);
    
    % Execute
    SQL.execute(sql);
end