function html = printInstructions(obj)
%printInstructions Convert instructions cell array of strings to HTML
%   Detailed explanation goes here

ins = obj.Instructions;
bullets_c = strcat('<li>', ins, '</li>');
bullets_c = bullets_c(:)';

html = [{...
'<div class="row">',...
'<div class="col-xs-12 col-md-12">',...
'<div class="panel panel-primary"><!-- WARNING: the ids "collapseTrigger" and "instructionBody" are being used to enable expand/collapse feature --><a class="panel-heading" href="javascript:void(0);" id="collapseTrigger"><strong>Image Transcription Instructions</strong> <span class="collapse-text">(Click to expand)</span> </a>',...
'<div class="panel-body" id="instructionBody">',...
'<p>Write the values from the image identified by columns.</p>',...
'<ul>'},...
bullets_c,...
{'</ul>',...
'</div>',...
'</div>',...
'</div>',...
'</div>'}];

html = html(:);

end