/* Update Air Resistance in no-wind condition */

USE hull_performance;

DROP PROCEDURE IF EXISTS createTempMarorkaRaw;

delimiter //

CREATE PROCEDURE createTempMarorkaRaw()
BEGIN

	DROP TABLE IF EXISTS tempMarorkaRaw;

	CREATE TABLE tempMarorkaRaw(
		 id INTEGER AUTO_INCREMENT PRIMARY KEY,
		`ShipName` 	TEXT,
		`IMONo` 	INT(7),
         DateTime_UTC 	DATETIME,
		`Timestamp` 	DATETIME,
		`Latitude` 	DOUBLE(20, 5),
		`Longitude` 	DOUBLE(20, 5),
		`State` 	TEXT,
		`Boiler consumed [MT]` 	DOUBLE(20, 5),
		`Aux consumed [MT]` 	DOUBLE(20, 5),
		`ME consumed [MT]` 	DOUBLE(20, 5),
		`Aux electrical power output [kW]` 	DOUBLE(20, 5),
		`Shaft power [kW]` 	DOUBLE(20, 5),
		`Shaft rpm [rpm]` 	DOUBLE(20, 5),
		`Draft fore [m]` 	DOUBLE(20, 5),
		`Draft aft [m]` 	DOUBLE(20, 5),
		`Relative wind speed [m/s]` 	DOUBLE(20, 5),
		`Relative wind direction [Â°]` 	DOUBLE(20, 5),
		`Relative wind direction [°]` 	DOUBLE(20, 5),
		`COG heading [Â°]` 	DOUBLE(20, 5),
		`COG heading [°]` 	DOUBLE(20, 5),
		`GPS speed [knots]` 	DOUBLE(20, 5),
		`Log speed [knots]` 	DOUBLE(20, 5),
		`Shaft generator power [kW]` 	DOUBLE(20, 5),
		`Sea depth [m]` 	DOUBLE(20, 5),
		`DG1 Power [kW]` 	DOUBLE(20, 5),
		`DG2 Power [kW]` 	DOUBLE(20, 5),
		`DG3 Power [kW]` 	DOUBLE(20, 5),
		`Propeller Pitch [m]` 	DOUBLE(20, 5),
		`Cargo weight [TEU]` 	DOUBLE(20, 5),
		`Shaft Torque [kNm]` 	DOUBLE(20, 5),
		`M.C.S.W_PRESS []` 	DOUBLE(20, 5),
		`SGM_ACTUAL_ACTIVE_POWER_ABSOLUTE []` 	DOUBLE(20, 5),
		`WHR - SM nominal electrical power [kW]` 	DOUBLE(20, 5),
		`WHR - SG nominal electrical power []` 	DOUBLE(20, 5),
		`SGM_MACHINE_POWER []` 	DOUBLE(20, 5),
		`WHR - SCM electrical power []` 	DOUBLE(20, 5),
		`ME_EXH_GAS_RECEIVER_PRESSURE []` 	DOUBLE(20, 5),
		`ME_EXH_GAS_PRESS_AT_TURBO_CHARGER_IN []` 	DOUBLE(20, 5),
		`MAIN_ENGINE_LOAD_SIGNAL_FOR_PGS []` 	DOUBLE(20, 5),
		`WHR - HP SH steam mass flow []` 	DOUBLE(20, 5),
		`WHR - HP SH steam temperature []` 	DOUBLE(20, 5),
		`WHR - HP SH steam pressure []` 	DOUBLE(20, 5),
		`WHR - LP circ. pump water-steam mass flow []` 	DOUBLE(20, 5),
		`WHR - LP FW temperature []` 	DOUBLE(20, 5),
		`WHR - LP SH steam temperature []` 	DOUBLE(20, 5),
		`WHR - LP SH steam pressure []` 	DOUBLE(20, 5),
		`PERFORMACE_LEVEL_HP_SECTION []` 	DOUBLE(20, 5),
		`PERFORMACE_LEVEL_LP_SECTION []` 	DOUBLE(20, 5),
		`WHR - ME exhaust gas mass flow calculated []` 	DOUBLE(20, 5),
		`WHR - HP SH steam inlet temperature []` 	DOUBLE(20, 5),
		`WHR - HP ST steam inlet pressure []` 	DOUBLE(20, 5),
		`WHR - LP ST steam inlet pressure []` 	DOUBLE(20, 5),
		`WHR - ST HP steam inlet temperature []` 	DOUBLE(20, 5),
		`WHR - ST LP steam inlet temperature []` 	DOUBLE(20, 5),
		`WHR - HP bypass steam inlet temperature []` 	DOUBLE(20, 5),
		`WHR - HP steam available power []` 	DOUBLE(20, 5),
		`WHR - Power turbine available power []` 	DOUBLE(20, 5),
		`WHR - ST steam nozzle pressure []` 	DOUBLE(20, 5),
		`WHR - Turbogenerator electrical power [kW]` 	DOUBLE(20, 5),
		`WHR - Turbogenerator nominal electrical power []` 	DOUBLE(20, 5),
		`WHR - HP circ. pump water-steam mass flow []` 	DOUBLE(20, 5),
		`WHR - Boiler HP exhaust gas pressure drop []` 	DOUBLE(20, 5),
		`WHR - Boiler HP exhaust gas pressure drop expected []` 	DOUBLE(20, 5),
		`WHR - Boiler LP exhaust gas pressure drop []` 	DOUBLE(20, 5),
		`WHR - Boiler LP exhaust gas pressure drop expected []` 	DOUBLE(20, 5),
		`WHR - LP bypass valve outlet temperature []` 	DOUBLE(20, 5),
		`WHR - LP bypass dump tube pressure []` 	DOUBLE(20, 5),
		`WHR - HP bypass valve outlet temperature []` 	DOUBLE(20, 5),
		`WHR - HP steam bypass dump tube pressure []` 	DOUBLE(20, 5),
		`WHR - Boiler LP pressure []` 	DOUBLE(20, 5),
		`WHR - Boiler HP pressure []` 	DOUBLE(20, 5),
		`WHR - ST HP inlet valve position []` 	DOUBLE(20, 5),
		`WHR - ST LP inlet valve position []` 	DOUBLE(20, 5),
		`WHR - LP bypass steam inlet temperature []` 	DOUBLE(20, 5),
		`WHR - HP steam dump valve position []` 	DOUBLE(20, 5),
		`WHR - LP steam dump valve position []` 	DOUBLE(20, 5),
		`Trim recommendation max [m]` 	DOUBLE(20, 5),
		`Trim recommendation min [m]` 	DOUBLE(20, 5),
		`Trim potential savings [%]` 	DOUBLE(20, 5),
		`ME load [%]` 	DOUBLE(20, 5),
		`Trim recommendation [m]` 	DOUBLE(20, 5),
		`GPS speed recommendation [knots]` 	DOUBLE(20, 5),
		`GPS speed recommendation min [knots]` 	DOUBLE(20, 5),
		`GPS speed recommendation max [knots]` 	DOUBLE(20, 5),
		`Shaft RPM recommendation [rpm]` 	DOUBLE(20, 5),
		`Shaft RPM recommendation min [rpm]` 	DOUBLE(20, 5),
		`Shaft RPM recommendation max [rpm]` 	DOUBLE(20, 5),
		`DG recommendation [num]` 	DOUBLE(20, 5),
		`DG potential savings [%]` 	DOUBLE(20, 5),
		`WHR Turbine Generator [kW]` 	DOUBLE(20, 5),
		`DG Group 1 No. Running Actual [-]` 	DOUBLE(20, 5),
		`DG Group 1 No. Running Recommended [-]` 	DOUBLE(20, 5),
		`DG Potential Savings 2 [%]` 	DOUBLE(20, 5),
		`ME Power [KW]` 	DOUBLE(20, 5),
        `DG4 Power [kW]` 	DOUBLE(20, 5),
        `Vessel progress [nm]` 	DOUBLE(20, 5),
        `CURRENT_RPM_OF_ENGINE []`  	DOUBLE(20, 5),
        `WHR - ST speed []`  	DOUBLE(20, 5),
        `WHR - HP FW pressure []`  	DOUBLE(20, 5),                        
		`WHR - HP ST steam dump valve available power []`  	DOUBLE(20, 5),
		`WHR - LP EVA water-steam pressure []`  	DOUBLE(20, 5),
        `ME Load measured [%]`  	DOUBLE(20, 5),                           
		`OO Conversion Pitch 1 [%]`  	DOUBLE(20, 5),                      
		`OO Conversion RPM 1 [rpm]`  	DOUBLE(20, 5),                      
		`OO Conversion Speed [knots]`  	DOUBLE(20, 5),                    
		`OO Conversion Trim [m]`  	DOUBLE(20, 5),
        `WHR - HP EVA water-steam pressure []`        	DOUBLE(20, 5),     
		`WHR - LP ST steam dump valve available power []`  	DOUBLE(20, 5),                          
		`WHR - ST water-steam outlet temperature []`  	DOUBLE(20, 5)
										);
END;