function html = printInstructions(obj, varargin)
%printInstructions Convert instructions cell array of strings to HTML
%   Detailed explanation goes here

ins_c = obj.Instructions;

html = [{...
'<div class="row">',...
'<div class="col-xs-12 col-md-12">',...
'<div class="panel panel-primary"><!-- WARNING: the ids "collapseTrigger" and "instructionBody" are being used to enable expand/collapse feature --><a class="panel-heading" href="javascript:void(0);" id="collapseTrigger"><strong>Image Transcription Instructions</strong> <span class="collapse-text">(Click to expand)</span> </a>',...
'<div class="panel-body" id="instructionBody">',...
[ins_c{:}],...
'</div>',...
'</div>',...
'</div>',...
'</div>'}];

html = html(:);

end