function insertWithoutDuplicates(fromTable, toTable, columns, duplicateCols)
%insertWithoutDuplicates Insert from table into table without duplicates.
%   Detailed explanation goes here

% Input
validateattributes(fromTable, {'char'}, {'vector'}, ...
    'insertWithoutDuplicates', 'fromTable', 1);
validateattributes(toTable, {'char'}, {'vector'}, ...
    'insertWithoutDuplicates', 'toTable', 2);
validateattributes(columns, {'char', 'cell'}, {'vector'}, ...
    'insertWithoutDuplicates', 'columns', 3);
columns = validateCellStr(columns, 'insertWithoutDuplicates', 'columns', 3);
validateattributes(duplicateCols, {'char', 'cell'}, {'vector'}, ...
    'insertWithoutDuplicates', 'columns', 4);
duplicateCols = validateCellStr(duplicateCols, 'insertWithoutDuplicates',...
    'duplicateCols', 4);

% Build comma separated lit of column names
ColumnsList = sprintf('%s, ', columns{:});
ColumnsList(end-1:end) = [];
enclosedColumnsList = ['(', ColumnsList, ')'];

% Build Where clause
abColName_cs = cellfun(@(x) strcat('a.', x, ' = b.', x), duplicateCols,...
    'Uni', 0);
abColNameAnd_s = strjoin(abColName_cs, ' AND ');
sqlWhere_s = [' WHERE ', abColNameAnd_s];
sqlCmd_s = ['INSERT INTO ', toTable, ' ', enclosedColumnsList ...
				' SELECT ' ColumnsList ...
					' FROM ' fromTable ' AS a '...
						' WHERE NOT EXISTS(SELECT ' ColumnsList ' FROM ' toTable ' AS b' ...
							sqlWhere_s, ...
                               ' );'];

% Connect to Database
conn_ch = ['driver=MySQL ODBC 5.3 ANSI Driver;', ...
    'Server=localhost;',  ...
    'Database=', 'test2', ';',  ...
    'Uid=root;',  ...
    'Pwd=HullPerf2016;'];
sqlConn = adodb_connect(conn_ch);

% Call SQL
adodb_query(sqlConn, sqlCmd_s);

end
