/* Creates RawData table, a table containing the "raw" ship data obtained from DNVGL EcoInsight "Manage Data" facility. */ 

DROP PROCEDURE IF EXISTS createForceSeaReports;

delimiter //

CREATE PROCEDURE createForceSeaReports()

BEGIN

CREATE TABLE ForceSeaReports (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
CONSTRAINT UniVesselDate UNIQUE(VesselIMONumber, ReportStartUtcTime),
    VesselName VARCHAR(100),                 
    VesselIMONumber INT(7),            
    VoyageNumber DOUBLE(10, 7),               
    DeparturePort VARCHAR(100),              
    DepartureLocalTime DATETIME,         
    DepartureUtcTime DATETIME,           
    DepartureTimeZone INT(3),
    DepartureIsDaylightTime VARCHAR(3),
    ArrivalPort VARCHAR(100),              
    ArrivalLocalTime DATETIME,          
    ArrivalUtcTime DATETIME,            
    ArrivalTimeZone INT(3),         
    ArrivalIsDaylightTime VARCHAR(3),   
    RemainingDistance DOUBLE(10, 7),          
    RemainingTime DOUBLE(10, 7),              
    ReportStartLocalTime DATETIME,       
    ReportStartUtcTime DATETIME,         
    ReportStartTimeZone INT(3),        
    ReportEndLocalTime DATETIME,         
    ReportEndUtcTime DATETIME,           
    ReportEndTimeZone INT(3),       
    ReportPeriod DOUBLE(10, 7),                 
    LatitudeDegrees DOUBLE(10, 7),            
    LatitudeMinutes DOUBLE(10, 7),            
    LatitudeSeconds DOUBLE(10, 7),            
    LatitudeSign CHAR(1),               
    LongitudeDegrees DOUBLE(10, 7),           
    LongitudeMinutes DOUBLE(10, 7),           
    LongitudeSeconds DOUBLE(10, 7),           
    LongitudeSign CHAR(1),              
    Heading DOUBLE(10, 7),                    
    DraughtAft DOUBLE(10, 7),                 
    DraughtFore DOUBLE(10, 7),                
    DistanceLogged DOUBLE(10, 7),             
    DistanceObserved DOUBLE(10, 7),           
    WindSpeed DOUBLE(10, 7),                  
    WindDirection DOUBLE(10, 7),              
    AirTemperature DOUBLE(10, 7),             
    MinimumWaterDepth DOUBLE(10, 7),          
    WaterTemperature DOUBLE(10, 7),           
    WavesState DOUBLE(10, 7),                 
    WavesDirection DOUBLE(10, 7),             
    MainEnginePower DOUBLE(10, 3),            
    TcSpeed DOUBLE(10, 7),                    
    PropellerSpeed DOUBLE(10, 7),             
    PumpIndex DOUBLE(10, 7),                  
    SGProduction DOUBLE(10, 7),               
    CPPropellerPitch DOUBLE(10, 7),           
    MainEngineHFOConsumption DOUBLE(10, 7),   
    MainEngineHFOLsConsumption DOUBLE(10, 7), 
    MainEngineMDOConsumption DOUBLE(10, 7),   
    MainEngineMDOLsConsumption DOUBLE(10, 7), 
    MainEngineMGOConsumption DOUBLE(10, 7),   
    MainEngineBioConsumption DOUBLE(10, 7),   
    TotalHFOConsumption DOUBLE(10, 7),        
    TotalHFOLsConsumption DOUBLE(10, 7),      
    TotalMDOConsumption DOUBLE(10, 7),        
    TotalMDOLsConsumption DOUBLE(10, 7),      
    TotalMGOConsumption DOUBLE(10, 7),        
    TotalBioConsumption DOUBLE(10, 7),        
    RemainingHFO DOUBLE(10, 7),               
    RemainingHFOLs DOUBLE(10, 7),             
    RemainingMDO DOUBLE(10, 7),               
    RemainingMDOLs DOUBLE(10, 7),             
    RemainingMGO DOUBLE(10, 7),               
    RemainingBio DOUBLE(10, 7),               
    LowerCalorificValueForHFO DOUBLE(10, 7),  
    LowerCalorificValueForHFOLs DOUBLE(10, 7),
    LowerCalorificValueForMDO DOUBLE(10, 7),  
    LowerCalorificValueForMDOLs DOUBLE(10, 7),
    LowerCalorificValueForMGO DOUBLE(10, 7),  
    LowerCalorificValueForBio DOUBLE(10, 7),  
    ShaftThrust DOUBLE(10, 7),                
    Comments VARCHAR(256),                   
    SpeedIndexCombined DOUBLE(10, 7),         
    ConsumptionIndexCombined DOUBLE(10, 7)
);

END;