/* Creates RawData table, a table containing the "raw" ship data obtained from DNVGL EcoInsight "Manage Data" facility. */ 

DROP PROCEDURE IF EXISTS createForceRaw;

delimiter //

CREATE PROCEDURE createForceRaw()

BEGIN

CREATE TABLE ForceRaw (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(100),
     imo_number INT(7),
     start DATETIME,
     xEnd DATETIME,
     lat_N INT(3),
     lat_t1 DATETIME,
     lat_t2 DATETIME,
     lat_mean DOUBLE(7, 5),
     lon_N  INT(3),
     lon_t1 DATETIME,
     lon_t2 DATETIME,
     lon_mean DOUBLE(7, 4),
     sog_N INT(3),
     sog_t1 DATETIME,
     sog_t2 DATETIME,
     sog_min DOUBLE(17, 7),
     sog_max DOUBLE(17, 7),
     sog_mean DOUBLE(17, 7),
     sog_std DOUBLE(17, 7),
     cog_N INT(3),
     cog_t1 DATETIME,
     cog_t2 DATETIME,
     cog_min DOUBLE(17, 7),
     cog_max DOUBLE(17, 7),
     cog_mean DOUBLE(17, 7),
     cog_std DOUBLE(17, 7),
     stw_N INT(3),
     stw_t1 DATETIME,
     stw_t2 DATETIME,
     stw_min DOUBLE(17, 7),
     stw_max DOUBLE(17, 7),
     stw_mean DOUBLE(17, 7),
     stw_std DOUBLE(17, 7),
     hdt_N INT(3),
     hdt_t1 DATETIME,
     hdt_t2 DATETIME,
     hdt_min DOUBLE(17, 7),
     hdt_max DOUBLE(17, 7),
     hdt_mean DOUBLE(17, 7),
     hdt_std DOUBLE(17, 7),
     wins_N INT(3),
     wins_t1 DATETIME,
     wins_t2 DATETIME,
     wins_min DOUBLE(17, 7),
     wins_max DOUBLE(17, 7),
     wins_mean DOUBLE(17, 7),
     wins_std DOUBLE(17, 7),
     wind_N INT(3),
     wind_t1 DATETIME,
     wind_t2 DATETIME,
     wind_min DOUBLE(17, 7),
     wind_max DOUBLE(17, 7),
     wind_mean DOUBLE(17, 7),
     wind_std DOUBLE(17, 7),
     airt_N INT(3),
     airt_t1 DATETIME,
     airt_t2 DATETIME,
     airt_min DOUBLE(17, 7),
     airt_max DOUBLE(17, 7),
     airt_mean DOUBLE(17, 7),
     airt_std DOUBLE(17, 7),
     airp_N INT(3),
     airp_t1 DATETIME,
     airp_t2 DATETIME,
     airp_min DOUBLE(17, 7),
     airp_max DOUBLE(17, 7),
     airp_mean DOUBLE(17, 7),
     airp_std DOUBLE(17, 7),
     rot_N INT(3),
     rot_t1 DATETIME,
     rot_t2 DATETIME,
     rot_min DOUBLE(17, 7),
     rot_max DOUBLE(17, 7),
     rot_mean DOUBLE(17, 7),
     rot_std DOUBLE(17, 7),
     rud_N INT(3),
     rud_t1 DATETIME,
     rud_t2 DATETIME,
     rud_min DOUBLE(17, 7),
     rud_max DOUBLE(17, 7),
     rud_mean DOUBLE(17, 7),
     rud_std DOUBLE(17, 7),
     pitch_N INT(3),
     pitch_t1 DATETIME,
     pitch_t2 DATETIME,
     pitch_min DOUBLE(17, 7),
     pitch_max DOUBLE(17, 7),
     pitch_mean DOUBLE(17, 7),
     pitch_std DOUBLE(17, 7),
     roll_N INT(3),
     roll_t1 DATETIME,
     roll_t2 DATETIME,
     roll_min DOUBLE(17, 7),
     roll_max DOUBLE(17, 7),
     roll_mean DOUBLE(17, 7),
     roll_std DOUBLE(17, 7),
     dpt_N INT(3),
     dpt_t1 DATETIME,
     dpt_t2 DATETIME,
     dpt_min DOUBLE(17, 7),
     dpt_max DOUBLE(17, 7),
     dpt_mean DOUBLE(17, 7),
     dpt_std DOUBLE(17, 7),
     spow_N INT(3),
     spow_t1 DATETIME,
     spow_t2 DATETIME,
     spow_min DOUBLE(17, 7),
     spow_max DOUBLE(17, 7),
     spow_mean DOUBLE(17, 7),
     spow_std DOUBLE(17, 7),
     srpm_N INT(3),
     srpm_t1 DATETIME,
     srpm_t2 DATETIME,
     srpm_min DOUBLE(17, 7),
     srpm_max DOUBLE(17, 7),
     srpm_mean DOUBLE(17, 7),
     srpm_std DOUBLE(17, 7),
     strq_N INT(3),
     strq_t1 DATETIME,
     strq_t2 DATETIME,
     strq_min DOUBLE(17, 7),
     strq_max DOUBLE(17, 7),
     strq_mean DOUBLE(17, 7),
     strq_std DOUBLE(17, 7),
     sthr_N INT(3),
     sthr_t1 DATETIME,
     sthr_t2 DATETIME,
     sthr_min DOUBLE(17, 7),
     sthr_max DOUBLE(17, 7),
     sthr_mean DOUBLE(17, 7),
     sthr_std DOUBLE(17, 7),
     piid INT,
     speed_index_propeller DOUBLE(15, 10),
     consumption_index_propeller DOUBLE(15, 10),
     speed_index_hull DOUBLE(15, 10),
     consumption_index_hull DOUBLE(15, 10),
     speed_index_combined DOUBLE(15, 10),
     consumption_index_combined DOUBLE(15, 10),
     distance_through_water DOUBLE(15, 12),
     fuel_oil_consumption_iso_corrected DOUBLE(16, 15),
     shaft_power_estimate DOUBLE(15, 5),
     shaft_power DOUBLE(15, 5),
     shaft_thrust DOUBLE(15, 5),
     shaft_power_estimate_from_rpm00 DOUBLE(15, 5),
     advance_ratio_estimate00 DOUBLE(16, 15),
     propeller_torque_coefficient DOUBLE(17, 7),
     propeller_tourque_coefficient_estimate00 DOUBLE(18, 17),
     propeller_tourque_coefficient_estimate01 DOUBLE(18, 17),
     propeller_thrust_estimate00 DOUBLE(16, 6),
     shaft_power_theoretical DOUBLE(15, 6),
     shaft_power_reference_condition_normalized DOUBLE(17, 7),
     shaft_power_estimate_reference_condition_normalized DOUBLE(17, 7),
     fuel_oil_consumption_reference_condition_normalized DOUBLE(17, 7),
     shaft_power_charter_party_condition_normalized DOUBLE(17, 7),
     shaft_power_estimate_charter_party_condition_normalized DOUBLE(17, 7),
     charter_party_seaState DOUBLE(17, 7),
     charter_party_wind DOUBLE(17, 7),
     fuel_oil_consumption_charter_party_condition_normalized DOUBLE(17, 7),
     loading_reference INT,
     shaft_power_loading_condition_normalized DOUBLE(18, 8),
     shaft_power_estimate_loading_condition_normalized DOUBLE(16, 7),
     fuel_oil_consumption_loading_condition_normalized DOUBLE(16, 7),
     specific_fuel_oil_consumption_reference DOUBLE(16, 15),
     specific_fuel_oil_consumption_normalized_to_reference_mcr DOUBLE(16, 15),
     towingresistanceestimate00          DOUBLE(16, 8),                  
     towingresistanceestimate01          DOUBLE(16, 8),                     
     towingresistanceestimate02          DOUBLE(16, 8),                     
     excessresistanceestimate00          DOUBLE(16, 8),                    
     excessresistanceestimate01          DOUBLE(16, 8),                   
     iso19030speedloss                   DOUBLE(16, 10),                      
     consolidateddepth                   DOUBLE(16, 15),
     type VARCHAR(5),
     average_speed DOUBLE(16, 13),
     report_start_utc DATETIME,
     report_end_utc DATETIME,
     remaining_distance INT, 
     heading DOUBLE(16, 15),
     report_lat DOUBLE(16, 14),
     report_lon DOUBLE(16, 13),
     draught_aft DOUBLE(16, 14),
     draught_fore DOUBLE(16, 14),
     distance_logged  DOUBLE(10, 6),
     distance_observed  DOUBLE(10, 6),
     wind_speed  DOUBLE(10, 7),
     wind_direction  DOUBLE(10, 7),
     air_temperature  DOUBLE(10, 7),
     barometric_pressure  DOUBLE(10, 7),
     sea_state INT,
     waves_direction DOUBLE(10, 9),
     min_water_depth DOUBLE(10, 4),
     water_temperature DOUBLE(10, 4),
     me_power DOUBLE(10, 4),
     me_turbo_charger_rpm DOUBLE(10, 4),
     propeller_rpm DOUBLE(5, 2),
     pump_index INT,
     sg_production DOUBLE(3, 2),
     cp_propeller_pitch DOUBLE(3, 2),
     cp_propeller_pitch_unit DOUBLE(3, 2),
     report_shaft_thrust DOUBLE(3, 2),
     main_engine_hfo_consumption  DOUBLE(10, 2),
     main_engine_hfo_ls_consumption DOUBLE(10, 2),
     main_engine_mdo_consumption DOUBLE(10, 2),
     total_hfo_consumption DOUBLE(10, 2),
     total_hfo_ls_consumption DOUBLE(10, 2),
     total_mdo_consumption DOUBLE(10, 2),
     remaining_hfo DOUBLE(5, 1),
     remaining_hfo_ls DOUBLE(5, 1),
     remaining_mdo DOUBLE(5, 1),
     main_engine_mdo_ls_consumption DOUBLE(5, 2),
     main_engine_mgo_consumption DOUBLE(5, 2),
     main_engine_bio_consumption DOUBLE(5, 2),
     total_mdo_ls_consumption DOUBLE(5, 2),
     total_mgo_consumption DOUBLE(5, 2),
     total_bio_consumption DOUBLE(5, 2),
     remaining_mdo_ls DOUBLE(5, 2),
     remaining_mgo DOUBLE(5, 2),
     remaining_bio DOUBLE(5, 2),
     lower_calorific_value_for_bio DOUBLE(5, 4),
     lower_calorific_value_for_hfo DOUBLE(6, 2),
     lower_calorific_value_for_ls_hfo DOUBLE(6, 2),
     lower_calorific_value_for_ls_mdo DOUBLE(6, 2),
     lower_calorific_value_for_mdo DOUBLE(6, 2),
     lower_calorific_value_for_mgo DOUBLE(6, 2),
     payload INT(10),
     payload_unit INT(10),
     voyagename VARCHAR(256),
     eventid INT(10),
     eventstart DATETIME,
     eventend DATETIME,
     eventname VARCHAR(256),
     filtered BOOL
);

END;