
    ShipName
    IMONo
    Timestamp
    Latitude
    Longitude
    State
    Boiler_consumed__MT_
    Aux_consumed__MT_
    ME_consumed__MT_
    Aux_electrical_power_output__kW_
    Shaft_power__kW_
    Shaft_rpm__rpm_
    Draft_fore__m_
    Draft_aft__m_
    Relative_wind_speed__m_s_
    Relative_wind_direction_____
    COG_heading_____
    GPS_speed__knots_
    Log_speed__knots_
    Shaft_generator_power__kW_
    Sea_depth__m_
    DG1_Power__kW_
    DG2_Power__kW_
    DG3_Power__kW_
    Propeller_Pitch__m_
    Cargo_weight__TEU_
    Shaft_Torque__kNm_
    M_C_S_W_PRESS___
    SGM_ACTUAL_ACTIVE_POWER_ABSOLUTE___
    WHR___SM_nominal_electrical_power__kW_
    WHR___SG_nominal_electrical_power___
    SGM_MACHINE_POWER___
    WHR___SCM_electrical_power___
    ME_EXH_GAS_RECEIVER_PRESSURE___
    ME_EXH_GAS_PRESS_AT_TURBO_CHARGER_IN___
    MAIN_ENGINE_LOAD_SIGNAL_FOR_PGS___
    WHR___HP_SH_steam_mass_flow___
    WHR___HP_SH_steam_temperature___
    WHR___HP_SH_steam_pressure___
    WHR___LP_circ__pump_water_steam_mass_flow___
    WHR___LP_FW_temperature___
    WHR___LP_SH_steam_temperature___
    WHR___LP_SH_steam_pressure___
    PERFORMACE_LEVEL_HP_SECTION___
    PERFORMACE_LEVEL_LP_SECTION___
    WHR___ME_exhaust_gas_mass_flow_calculated___
    WHR___HP_SH_steam_inlet_temperature___
    WHR___HP_ST_steam_inlet_pressure___
    WHR___LP_ST_steam_inlet_pressure___
    WHR___ST_HP_steam_inlet_temperature___
    WHR___ST_LP_steam_inlet_temperature___
    WHR___HP_bypass_steam_inlet_temperature___
    WHR___HP_steam_available_power___
    WHR___Power_turbine_available_power___
    WHR___ST_steam_nozzle_pressure___
    WHR___Turbogenerator_electrical_power__kW_
    WHR___Turbogenerator_nominal_electrical_power___
    WHR___HP_circ__pump_water_steam_mass_flow___
    WHR___Boiler_HP_exhaust_gas_pressure_drop___
    WHR___Boiler_HP_exhaust_gas_pressure_drop_expected___
    WHR___Boiler_LP_exhaust_gas_pressure_drop___
    WHR___Boiler_LP_exhaust_gas_pressure_drop_expected___
    WHR___LP_bypass_valve_outlet_temperature___
    WHR___LP_bypass_dump_tube_pressure___
    WHR___HP_bypass_valve_outlet_temperature___
    WHR___HP_steam_bypass_dump_tube_pressure___
    WHR___Boiler_LP_pressure___
    WHR___Boiler_HP_pressure___
    WHR___ST_HP_inlet_valve_position___
    WHR___ST_LP_inlet_valve_position___
    WHR___LP_bypass_steam_inlet_temperature___
    WHR___HP_steam_dump_valve_position___
    WHR___LP_steam_dump_valve_position___
    Trim_recommendation_max__m_
    Trim_recommendation_min__m_
    Trim_potential_savings____
    ME_load____
    Trim_recommendation__m_
    GPS_speed_recommendation__knots_
    GPS_speed_recommendation_min__knots_
    GPS_speed_recommendation_max__knots_
    Shaft_RPM_recommendation__rpm_
    Shaft_RPM_recommendation_min__rpm_
    Shaft_RPM_recommendation_max__rpm_
    DG_recommendation__num_
    DG_potential_savings____
    WHR_Turbine_Generator__kW_
    DG_Group_1_No__Running_Actual____
    DG_Group_1_No__Running_Recommended____
    DG_Potential_Savings____
    ME_Power__KW_